YouFood\MainBundle\Entity\Theme:
    xml_root_name: theme
    properties:
        id:
            groups: [id]
        name:
            groups: [theme_small, theme_full]
        weeks:
            groups: [theme_full]
        products:
            groups: [theme_full]
