YouFood\MainBundle\Entity\Category:
    xml_root_name: category
    properties:
        id:
            groups: [id]
        name:
            groups: [category_small, category_full]
        collations:
            groups: [category_full]
