YouFood\MainBundle\Entity\Week:
    xml_root_name: week
    properties:
        id:
            groups: [id]
        year:
            groups: [week_small, week_full]
        weekNumber:
            groups: [week_small, week_full]
        theme:
            groups: [week_small, week_full]
