YouFood\MainBundle\Entity\Order:
    xml_root_name: order
    properties:
        id:
            groups: [id]
        date:
            groups: [order_small, order_full]
        collationOrders:
            groups: [order_small, order_full]
        menuOrders:
            groups: [order_small, order_full]
        table:
            groups: [order_small, order_full]
        paid:
            groups: [order_small, order_full]
