YouFood\MainBundle\Entity\Product:
    xml_root_name: product
    properties:
        id:
            groups: [id]
        themes:
            groups: [product_full]
        name:
            groups: [product_small, product_full]
        price:
            groups: [product_list, product_full]
