parameters:
    you_food.admin.category.class: YouFood\MainBundle\Admin\CategoryAdmin
    you_food.admin.collation.class: YouFood\MainBundle\Admin\CollationAdmin
    you_food.admin.menu.class: YouFood\MainBundle\Admin\MenuAdmin
    you_food.admin.theme.class: YouFood\MainBundle\Admin\ThemeAdmin
    you_food.admin.week.class: YouFood\MainBundle\Admin\WeekAdmin
    you_food.admin.collation_order.class: YouFood\MainBundle\Admin\CollationOrderAdmin
    you_food.admin.menu_order.class: YouFood\MainBundle\Admin\MenuOrderAdmin
    you_food.admin.order.class: YouFood\MainBundle\Admin\OrderAdmin
    you_food.admin.request.class: YouFood\MainBundle\Admin\RequestAdmin
    you_food.admin.restaurant.class: YouFood\MainBundle\Admin\RestaurantAdmin
    you_food.admin.table.class: YouFood\MainBundle\Admin\TableAdmin
    you_food.admin.zone.class: YouFood\MainBundle\Admin\ZoneAdmin
    you_food.admin.menu_has_collation.class: YouFood\MainBundle\Admin\MenuHasCollationAdmin

services:
    you_food.admin.category:
        class: %you_food.admin.category.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Category
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.menu, label: Category }

    you_food.admin.collation:
        class: %you_food.admin.collation.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Collation
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.menu, label: Collation }

    you_food.admin.menu:
        class: %you_food.admin.menu.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Menu
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.menu, label: Menu }

    you_food.admin.theme:
        class: %you_food.admin.theme.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Theme
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.menu, label: Theme }

    you_food.admin.week:
        class: %you_food.admin.week.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Week
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.menu, label: Week }

    you_food.admin.collation_order:
        class: %you_food.admin.collation_order.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\CollationOrder
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.order, label: CollationOrder }

    you_food.admin.menu_order:
        class: %you_food.admin.menu_order.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\MenuOrder
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.order, label: MenuOrder }

    you_food.admin.order:
        class: %you_food.admin.order.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Order
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.order, label: Order }

    you_food.admin.request:
        class: %you_food.admin.request.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Request
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.order, label: Request }

    you_food.admin.restaurant:
        class: %you_food.admin.restaurant.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Restaurant
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.management, label: Restaurant }

    you_food.admin.table:
        class: %you_food.admin.table.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Table
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Table }

    you_food.admin.zone:
        class: %you_food.admin.zone.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\Zone
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, group: you_food.management, label: Zone }

    you_food.admin.menu_has_collation:
        class: %you_food.admin.menu_has_collation.class%
        arguments:
          - ~
          - YouFood\MainBundle\Entity\MenuHasCollation
          - SonataAdminBundle:CRUD
        calls:
          - [ setTranslationDomain, [ YouFood\Admin\MainBundle ] ]
        tags:
          - { name: sonata.admin, manager_type: orm, label: MenuHasCollation }
