YouFood\MediaBundle\Entity\Media:
    xml_root_name: media
    properties:
        id:
            groups: [id]
        urlSmall:
            groups: [id] # always
        urlBig:
            groups: [id] # always