categories:
    type:     rest
    resource: YouFood\ApiBundle\Controller\CategoriesController

collations:
    type:     rest
    resource: YouFood\ApiBundle\Controller\CollationsController

menus:
    type:     rest
    resource: YouFood\ApiBundle\Controller\MenusController

themes:
    type:     rest
    resource: YouFood\ApiBundle\Controller\ThemesController

weeks:
    type:     rest
    resource: YouFood\ApiBundle\Controller\WeeksController

restaurants:
    type:     rest
    resource: YouFood\ApiBundle\Controller\RestaurantsController

zones:
    type:     rest
    resource: YouFood\ApiBundle\Controller\ZonesController

tables:
    type:     rest
    resource: YouFood\ApiBundle\Controller\TablesController

table_orders:
    type:     rest
    parent:   tables
    resource: YouFood\ApiBundle\Controller\TableOrdersController

users:
    type:     rest
    resource: YouFood\ApiBundle\Controller\UsersController

user_tables:
    type:     rest
    parent:   users
    resource: YouFood\ApiBundle\Controller\UserTablesController

orders:
    type:     rest
    resource: YouFood\ApiBundle\Controller\OrdersController

requests:
    type:     rest
    resource: YouFood\ApiBundle\Controller\RequestsController
