category:
    type:     rest
    resource: YouFood\ApiBundle\Controller\CategoryController

collation:
    type:     rest
    resource: YouFood\ApiBundle\Controller\CollationController

menu:
    type:     rest
    resource: YouFood\ApiBundle\Controller\MenuController

theme:
    type:     rest
    resource: YouFood\ApiBundle\Controller\ThemeController

week:
    type:     rest
    resource: YouFood\ApiBundle\Controller\WeekController

order:
    type:     rest
    resource: YouFood\ApiBundle\Controller\OrderController

restaurant:
    type:     rest
    resource: YouFood\ApiBundle\Controller\RestaurantController

zone:
    type:     rest
    resource: YouFood\ApiBundle\Controller\ZoneController

table:
    type:     rest
    resource: YouFood\ApiBundle\Controller\TableController
